### ISSUE TITLE
Build issue in Windows due to toolchain

### ISSUE THREAD

**Issue by xlouis027** [nihalpasham/rustBoot#10]
Hi all,
I have tried to compile and build rustBoot on Windows. When I set to nightly (nightly-x86_64-pc-windows-msvc), I face to this error:

> 

> PS D:\Rust\rustBoot> cargo xtask build-sign-flash rustBoot nrf52840
   Compiling xtask v0.1.0 (D:\Rust\rustBoot\xtask)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.10zrahq0ct7ie1kq.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.11yv8jm96n8ck2g3.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.12waeh2yapqnuxkn.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.13mu7d720nrys3hq.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1887fvruxi4hkcuh.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1ag6mao993j9e25.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1cf6hba0unm2qeys.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1jid1qxcrv7ehk93.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1m1dyp3d6mtyycc4.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1wgptagz904k7p07.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.1wqypglyaf00u3r9.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.243ifb2w5fnl8yyc.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2440ds706iz49f6t.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2aslgu09oynkptme.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2br3ubn01wfv3ert.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2c49wbx7xmv7ri6w.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2dlvzihqx4qrczh6.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2g9khjj5r7usq86c.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2ki16w91nexwith6.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2m1n10zysmjvvzy.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2nrm31xruaalg4ry.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2pv8tfj0kbr3ijdx.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2pxg04pbk458fq7w.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2q2f2hjtpp1pycfl.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.2wvdpqfbvok9xsf9.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.34l1h754ivate3k.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.36dath1lt8ldmi4d.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3elsavyr477bk3jm.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3f0s19kqtzvckfmg.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3gjjugz0f8z4x2za.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3gxkand5t2jos48e.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3ohd3f84gysdjmhi.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3qcn0a8lipmjyiuu.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3ucomvf372qxo147.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3vkwzuhcpl8g8drp.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3wp9ij24d8aj7k2c.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3xzuotiuf7s9qcsz.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.3zx0uhia4j1nd8hw.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.460bywmz7n51ol4w.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.49tghx9nvk762kch.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4b33nncmec1is9hf.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4i568fpcvgc68b09.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4ke5paun12r7z1ok.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4knwyrkq7koj3jp.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4kou600ew92hpq2r.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4kwvh4tdvq4g56i1.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4o3x10gjkyx4e50s.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4v26y4vmbero89th.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.4ybtx91zhxcl5gnt.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.51q26rucibbgtbef.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.55r07zcxvnswnit8.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.7hdnf4i2d0kb84q.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.99n3kp4grqd49kd.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.bjdfyn63wvnm9zl.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.ej7gz5omvz3oxbj.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.ostn8ce0hao362t.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.xzmgupirrawq4tm.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.z0s3cy11woong10.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.ztcagat28r9muxt.rcgu.o" "D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.5ccptqy7k36900z9.rcgu.o" "/LIBPATH:D:\\Rust\\rustBoot\\target\\debug\\deps" "/LIBPATH:D:\\Rust\\rustBoot\\target\\debug\\build\\defmt-0312fcda029d8a93\\out" "/LIBPATH:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libanyhow-889e1d5c5ce55de2.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libxshell-e5ab19e67fe61b78.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\librustBoot-2b6bd830c403f363.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libnom-7c1ff9e36a84177d.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libmemchr-070d3c24fd04df62.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libdefmt-4b894d4929c16506.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libp256-c04a47e9c84dd93a.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libsha2-43102365c4b23b5f.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libcpufeatures-9d8a08f29f58f6c3.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libcfg_if-b01931459ea167fc.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libopaque_debug-4883419788e55551.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libblock_buffer-dd1ac6ac4cfea08d.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libecdsa-9374177494f3853b.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libsignature-e4073c033e79d9d9.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libhmac-a34009256324a971.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libdigest-87773c94c8960f94.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libcrypto_mac-418adc1965a4b1ea.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libder-a9d06eb49c9b8942.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libelliptic_curve-9a587acf13e4e3d8.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libcrypto_bigint-b8c1fac78962db5b.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libgroup-590a7fce134fe30d.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libff-ff25d6cfe4d40b0f.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\librand_core-4cc1d6a3585099d8.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libzeroize-26869226754f3a98.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libgeneric_array-02ec51fcdb956bc7.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libtypenum-b1793961ce700d11.rlib" "D:\\Rust\\rustBoot\\target\\debug\\deps\\libsubtle-40eab3c15edc7bfb.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-0f7e1853181d29c2.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-ee8804a073a629b8.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-f320e82b0baaad6d.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-cede8d1fca99fc93.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-a6db156d99b5f701.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-31a385e2e15a7a71.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-c431fe701788effd.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-9c55022353a90ed5.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-5c6e234e3431724c.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-c4009c6b42e3b42a.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-665ed95809278e59.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-c2100e40c13f915d.rlib" "C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-e57a7d82dcc1d66d.rlib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:D:\\Rust\\rustBoot\\target\\debug\\deps\\xtask.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Admin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: libdefmt-4b894d4929c16506.rlib(defmt-4b894d4929c16506.defmt.153a5f11-cgu.12.rcgu.o) : error LNK2019: unresolved external symbol _defmt_acquire referenced in function _ZN5defmt6export7acquire17he8397d0b502dd5f8E
          libdefmt-4b894d4929c16506.rlib(defmt-4b894d4929c16506.defmt.153a5f11-cgu.12.rcgu.o) : error LNK2019: unresolved external symbol _defmt_release referenced in function _ZN5defmt6export7release17h9c88e361c85610ffE
          libdefmt-4b894d4929c16506.rlib(defmt-4b894d4929c16506.defmt.153a5f11-cgu.12.rcgu.o) : error LNK2019: unresolved external symbol _defmt_timestamp referenced in function _ZN5defmt6export9timestamp17he4ccfc9bd2c739beE
          libdefmt-4b894d4929c16506.rlib(defmt-4b894d4929c16506.defmt.153a5f11-cgu.12.rcgu.o) : error LNK2019: unresolved external symbol _defmt_panic referenced in function _ZN5defmt6export5panic17ha99baa72aa2f80d9E
          D:\Rust\rustBoot\target\debug\deps\xtask.exe : fatal error LNK1120: 4 unresolved externals
 error: could not compile `xtask` due to previous error

Am I have any missing step?

**Comment by nihalpasham** [comment]
Can you do a git-pull and try now?
