### ISSUE TITLE
[Question] Toolchain and rustup packages

### ISSUE THREAD

**Issue by xlouis027** [nihalpasham/rustBoot#11]
Hi Nihal,
I saw that in board nrf52840 use target `thumbv7em-none-eabihf` and rpi4 use target `aarch64-unknown-none-softfloat`.
I checked it and found reference on [https://rust-lang.github.io/rustup-components-history/](url).
My question is how we know a board use what suitable target rustup package?
Another point, what is the differences of **stable** and **nightly** toolchains, of `x86_64-pc-windows-msvc` and `x86_64-pc-windows-gnu`?

**Comment by nihalpasham** [comment]
`Rust` support for different platforms ("targets") are organized into three tiers, each with a different set of guarantees. You can find more information - https://doc.rust-lang.org/nightly/rustc/platform-support.html

Stable - the rust compiler (used to compile rust programs) is stable
nightly -  the rust compiler (used to compile rust programs) is not-stable i.e. it has some additions that are still under evaluation or testing.
