### ISSUE TITLE
How to support rpi3/rpi4 in rustBoot

### ISSUE THREAD

**Issue by datnguyentien1981** [nihalpasham/rustBoot#3]
**Dear Nihal**

I understand that the current source code only supports for nrf52840. In case, I want to modify rustboot to support rpi3/rpi4, I have to modify hardware abstraction layer in rpi3.rs/rpi4.rs and something else

 **Below are steps to support rpi3 in wolfBoot.**
**Compiling the kernel**

- Get raspberry-pi linux kernel:
git clone https://github.com/raspberrypi/linux linux-rpi -b rpi-4.19.y --depth=1
- Build kernel image:
cd linux-rpi
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
- Copy Image and .dtb to the wolfboot directory
cp Image arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b.dtb $wolfboot_dir
cd $wolfboot_dir

**Testing with qemu-system-aarch64**
- Build wolfboot using the example configuration (RSA4096, SHA3)
cp config/examples/raspi3.config .config
make wolfboot-align.bin
- Sign Image
tools/keytools/sign.py --rsa4096 --sha3 Image rsa4096.der 1
- Compose the image
cat wolfboot-align.bin Image_v1_signed.bin >wolfboot_linux_raspi.bin
dd if=bcm2710-rpi-3-b.dtb of=wolfboot_linux_raspi.bin bs=1 seek=128K conv=notrunc
- Test boot using qemu
qemu-system-aarch64 -M raspi3 -m 512 -serial stdio -kernel wolfboot_linux_raspi.bin -append "terminal=ttyS0 rootwait" -dtb ./bcm2710-rpi-3-b.dtb -cpu cortex-a53

 **Could you please advise me how to support rpi3/rpi4 in your rustboot.**

 **Dat Nguyen**

**Comment by nihalpasham** [comment]
Hi @datnguyentien1981 

We're in the process of porting rustBoot over to rpi4. This should be ready in sometime (no ETA yet). As our goal is to port rustBoot to a physical board (i.e. raspberry-pi4) and not an emulator, the steps involved in porting rustBoot to a new board are as follows -

1. **flash-api:** implement the `FlashInterface` trait for your board (abstracts out the necessary HW-specific flash operations such as writing/readin/erasing). This means, we'll need to implement a (flash) driver for a given board. In the case of rpi4, I'm porting a `C based SDCard driver` over to rust. Once this is done, we'll need choose a suitable a memory layout and implement the `UpdateInterface` trait.
2. **memory-layout:** choose a suitable memory layout (for boot + update partitions) based on the board's micro-architecture and make. 
3. **firmware-api:** use the methods from the `UpdateInterface` trait in your firmware to trigger and confirm firmware updates. (note - downloading and installing the update is to be handled by whatever firmware/OS you're running).

Notes: 

- Firmware updates involving `cortex-a + Linux + dtb` are usually done in RAM i.e. unlike in the case of nrf52840 (or bare-metal, cortex-m systems), where we need to swap boot and update flash partitions for every update.
- If you're interested in contributing to rpi4 port, please feel to take a look at the `work-in-progress` driver at `.\boards\test_impls\rpi4\src\bsp\drivers\sdhost.rs`
