### ISSUE TITLE
Upgrade board specific dependencies

### ISSUE THREAD

**Issue by imrank03** [nihalpasham/rustBoot#56]
If I try to upgrade board specific dependencies I get `Cortex-m-rt` conflicts error, because all board specific dependencies depend on `Cortex-m-rt` version number `0.6.15`. All board specific and `Cortex-m-rt` dependencies need to be updated.

**Comment by nihalpasham** [comment]
can you submit a a PR for this.

**Comment by imrank03** [comment]
I have submitted a PR for this.
