### ISSUE TITLE
The value of State

### ISSUE THREAD

**Issue by vietle77** [nihalpasham/rustBoot#6]
Hi Nihal,

Kindly clear me how do below values come with corresponding state:
StateNew : 0xFF
StateUpdating: 0x70
StateTesting: 0x10
StateSuccess: 0x00

Thank you,
Viet

**Comment by nihalpasham** [comment]
So, rustBoot uses (its own) state-ids to represent the state of a (boot/update) partition. The state-id is actually a single-byte identifier that lives at the end of boot/update partition. It looks something like this - on flash-memory

```sh
[...header...][...padding...][....firmware image....][.... free space....][...partition sector flags...][single byte partition status][4-byte trailer magic]
```

1. StateNew or (0xFF) means the image was never staged for boot, or triggered for an update. 
2. StateUpdating or (0x70): This is only valid in the `update` partition. This basically means that the OS/firmware has marked an image as `ready for update` and should replace the current image in the boot partition on the next reboot.
3. StateTesting or (0x10): This is only valid in the `boot` partition. It means the image has just been updated, and is pending a reboot. If we see the same state after a reboot, it means that the updated image failed to boot, despite being correctly verified. This particular situation triggers a rollback.
4. StateSuccess (0x00): This is only valid in the `boot` partition. It means the new image is stored in `boot` has been successfully staged at least once, and the update is now complete.
