### ISSUE TITLE
Add support for the nRF9160

### ISSUE THREAD

**Issue by macthestack** [nihalpasham/rustBoot#66]
The nRF9160 has some very interesting use cases opening up lte-m and nb-iot capabilities.

**Comment by nihalpasham** [comment]
yeah, it'd be a nice addition. Are you (already) working on adding rustBoot support for the nrf9160?

**Comment by nihalpasham** [comment]
@Strange21 -

**Comment by Strange21** [comment]
Acknowledged 👍

**Comment by nihalpasham** [comment]
closing this one. this is being tracked in #69
